---
title: "visualization"
author: "Cory Brunson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# session library
library(tidyverse)
#library(tidymodels)
library(landmark)
library(simplextree)
# source directories
rt_data <- "~/Desktop/rt-data"
# all care units
careunits <- read_rds(file.path(rt_data, "mimic-units.rds"))
careunits <- setdiff(careunits, c("NICU", "NWARD"))
```

```{r loop parameters}
careunit <- "CCU"
n_lmks <- 24L
```

```{r}
# binary data with cross-validation indices
file.path(rt_data, str_c("mimic-", tolower(careunit), "-cases.rds")) %>%
  read_rds() %>%
  print() -> unit_cases
# binary predictor and response matrices
unit_pred <- unit_cases %>%
  select(-subject_id, -hadm_id, -contains("mortality")) %>%
  mutate_all(as.integer) %>%
  as.matrix()
unit_resp <- unit_cases %>%
  select(mortality_hosp) %>%
  mutate_all(as.integer) %>%
  as.matrix()
# landmark selection and cover construction
unit_lmks_mm <- landmarks_maxmin(unit_pred, dist_method = "cosine",
                                 num = n_lmks, seed_index = "minmax",
                                 cover = TRUE,
                                 extend_radius = extension(mult = .25))
unit_lmks_lf <- landmarks_lastfirst(unit_pred, dist_method = "cosine",
                                    num = n_lmks, seed_index = "firstlast",
                                    cover = TRUE,
                                    extend_cardinality = extension(mult = .25))
# visualize and annotate overlapping covers
(unit_nerve_mm <- nerve(unit_pred, unit_lmks_mm))
(unit_nerve_lf <- nerve(unit_pred, unit_lmks_lf))
```
